version: '3'
services:
  shiny-devel:
    image: rocker/shiny:devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_shiny_devel
  shiny-verse-devel:
    image: rocker/shiny-verse:devel
    depends_on:
      - shiny-devel
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile_shiny-verse_devel
